disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "dracoboost gallery"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "dracoboost.png"

  [params.author]
  links = [ ]

["params.author"]
name = "dracoboost"
image = "avatar.png"
headline = "HoHatch Developer"
