disabled = false
languageCode = "ja"
languageName = "Japanese"
weight = 1
title = "dracoboost gallery"

[params]
displayName = "JA"
isoCode = "ja"
rtl = false
dateFormat = "2006/1/2"
logo = "maliss.jpg"
description = "dracoboostのブログと作成したソフトウェアの配布"

[params.author]
name = "dracoboost"
image = "avatar.png"
headline = "HoHatch Developer"

[[params.author.links]]
github = "https://github.com/dracoboost"
x-twitter = "https://twitter.com/dracoboost"
